### PR TITLE
Fix Digest authentication

### PR DESCRIPTION
**Pull request by catwell**
This pull requests fixes two bugs in the HTTP Digest authentication implementation.

### CODE REVIEW

**Comment by jmettraux** [comment]
Hello Pierre,

many thanks for the patch. It motivated me for renovating the project a bit. I didn't know it still held some value.

Cheers,

John

**Comment by catwell** [comment]
At least I use it :) I prefer it to HTTParty for instance.

Thanks for merging.

**Comment by catwell** [comment]
Could you release the fixed version on Rubygems please?

**Comment by jmettraux** [comment]
Hello,

it's pushed ( https://rubygems.org/gems/rufus-verbs ), please tell me if there is anything wrong.

Cheers,

**Comment by catwell** [comment]
It works great, thanks.

**Pull request merged**
